### ISSUE TITLE
Is there anyway to use pins that can't be unexported?

### ISSUE THREAD

**Issue by phuclv90** [warthog618/gpiod#27]
When I use gpiod on my board, some of the Lines can't be requested. It turns out those are exported in `/sys/class/gpio/`. When I unexport them they can be acquired properly. Unfortunately many pins can't be unexported. `echo $PIN_NUM > /sys/class/gpio/unexport` returns `sh: write error: Invalid argument`

I don't know which process or driver is holding them. How can I use them with gpiod?

**Comment by warthog618** [comment]
There is no way - you have to get whatever process or driver that is holding them to release them.

What does `gpioinfo`, or equivalently `gpiodctl info` show for those lines?  It may indicate who is holding them - though there is no guarantee - that depends on the holder.
