### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by itstmyi** [warthog618/gpiod#28]
when I run "go get -u github.com/warthog618/gpiod" 
from Windows 10 command prompt, I got the following message :

..\gpiod.go:326:30: undefined: uapi.LineInfo
..\gpiod.go:351:32: undefined: uapi.LineInfoV2
..\gpiod.go:391:21: undefined: uapi.LineInfo
..\gpiod.go:401:23: undefined: uapi.LineInfoV2
...

Had I make any mistakes ? Should I run it on Linux system ?
Thanks for any advice .

**Comment by warthog618** [comment]
So go get pays attention to build flags.  Nice.

`set GOOS=linux`
(literally that on your command line)
then do your go get.

Although the better solution would be to ditch Windows for Linux, as you suggest ;-).
