### ISSUE TITLE
Software PWM

### ISSUE THREAD

**Issue by maltegrosse** [warthog618/gpiod#29]
Hi,
Is it possible to include software pwm handling using non pwm pins as a pwm replacement?
E.g
https://github.com/WiringPi/WiringPi/blob/master/wiringPi/softPwm.c

**Comment by warthog618** [comment]
Yes and no.
It is trivial enough to do it in Go using gpiod to drive the pins.
But PWM is conceptually a separate API and I would rather keep the scope of this library to strictly GPIO.

**Comment by maltegrosse** [comment]
So e.g. adopting the wiring pi in go would be trivial? I don’t plan to use real pwm pins, just use normal gpios to control a fan, as my board does not have pwm headers but a lot of spare gpios

**Comment by warthog618** [comment]
I repeat - It is trivial enough to do it in Go using gpiod to drive the pins.
You can easily write a goroutine that does what the wiringpi code does that in softPwmThread.

**Comment by maltegrosse** [comment]
All right, than I will try it out once I got some time and will provide some example here

**Comment by Klaus-Tockloth** [comment]
@maltegrosse : Did you find a solution for software generated PWM?

**Comment by maltegrosse** [comment]
@Klaus-Tockloth I have not continue working on this - sorry.

**Comment by warthog618** [comment]
@maltegrosse @Klaus-Tockloth There is work being done on a [kernel driver](https://lore.kernel.org/linux-gpio/20210117130434.663qpp6noujptdyt@pengutronix.de/) for this, that would take any GPIO and present it to userspace as a PWM.  It is still a work in progress, so it hasn't hit the kernel yet, but I would be looking at using that when it does.

**Comment by Klaus-Tockloth** [comment]
Implementation in a kernel driver ... that sounds promising. Should we open a separate issue for this? Probably others are also interested in software generated PWM for any pin.

BTW: I have tried to write a Golang package for software generated PWM. The solution is based on go routines and time.Sleep(). But I ran into limitations (probably with the unsufficient resolution of time.Sleep()).

**Comment by warthog618** [comment]
@Klaus-Tockloth The timer resolution, particularly using time.Sleep(), and context switching overhead would definitely limit what you can do from userspace.

I think this issue is sufficient, and the driver itself is out of the scope of this library.

I must chase up where that driver is at when I have a chance - seems quite a few people are interested in it, particularly with the Pi community moving towards standard Linux interfaces.
