### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by ea7kir** [warthog618/gpiod#38]
GPIOD works perfectly for me and I'm grateful the work you are doing.
So, I would like to ask if you will consider adding 1-Wire and I2C support?

**Comment by warthog618** [comment]
No.  I would use the kernel subsystems for those protocols before considering bit-bashing them from userspace using GPIO.

**Comment by ea7kir** [comment]
Hi Kent.  If only I knew how.  Can you point me to any examples?

**Comment by warthog618** [comment]
[i2c](https://www.kernel.org/doc/html/latest/i2c/dev-interface.html)
[1-wire](https://www.kernel.org/doc/html/latest/w1/w1-generic.html)

Now you know as much as I do.
