### ISSUE TITLE
constants for AsOutput()

### ISSUE THREAD

**Issue by vu3rdd** [warthog618/gpiod#42]
It would be nice if some constants are defined and exported for the `AsOutput()` parameter (i.e. instead of giving a 0 or 1, some descriptive names would make it a lot easier to read).

**Comment by warthog618** [comment]
Something like:

```go
const (
    Inactive = 0
    Active = 1
)
```
?

IIRC, I didn't add those are the time as they don't really add much - 0/1 is pretty clear and seemed more idiomatic Go, and that is the value returned by the kernel.

The other problem I have with providing names is different people prefer different conventions.  Some like up/down, or hi/lo, or on/off, or...

Are you referring to the readability of the library itself or your own code?  If the latter have you added constants yourself?
